# NOTE: Do not edit, file was generated by jhconvert

Name: python-abiword
Version: 0.7.8
Release: %mkrel 2
Summary: Python bindings for libabiword
License: GPL+
Group: Development/Python
Url: http://abisource.com/

Source: http://www.abisource.com/downloads/pyabiword/0.7.8/pyabiword-0.7.8.tar.gz

Requires: abiword >= 2.7.6
Requires: pygtk2.0  
Requires: python  

BuildRequires: abiword-devel >= 2.7.6
BuildRequires: pygtk2.0-devel  
BuildRequires: libpython-devel  

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)


%description
This package installs Python bindings for libabiword.

%prep
%setup -q -n pyabiword-0.7.8


%build
%define __libtoolize true
%configure am_cv_python_pyexecdir=%{python_sitelib}
make

%install
rm -rf %{buildroot}
make DESTDIR=%{buildroot} install


%clean
rm -rf %{buildroot}

%files 
%defattr(-,root,root,-)
%{python_sitelib}/*
%{_datadir}/pygtk/2.0/defs/*.defs
%doc AUTHORS COPYING

