# NOTE: Do not edit, file was generated by jhconvert

Name: python-abiword
Version: 0.6.1
Release: %mkrel 1
Summary: Python bindings for libabiword
License: GPL+
Group: Development/Python
Url: http://abisource.com/

Source: http://www.sugarlabs.org/~marco/jhbuild/pyabiword-0.6.1.tar.gz

Requires: pygtk2.0  
Requires: python  
Requires: abiword >= 2.6.5

BuildRequires: pygtk2.0-devel  
BuildRequires: libpython-devel  
BuildRequires: abiword-devel >= 2.6.5

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)

%description
This package installs Python bindings for libabiword.

%prep
%setup -q -n pyabiword-0.6.1


%build
%configure  \
	am_cv_python_pyexecdir=%{python_sitelib}
make 

%install
rm -rf %{buildroot}
make  \
	install \
	DESTDIR=%{buildroot}

%clean
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
%{python_sitelib}/*
%{_datadir}/pygtk/2.0/defs/*.defs
%doc AUTHORS COPYING

